version: 2

defaults: &defaults
  working_directory: /tmp/workspace
  environment:
    TZ: "/usr/share/zoneinfo/Europe/Paris"
    NODE_ENV: test
  docker:
    - image: circleci/node:10.5.0-stretch-browsers

jobs:
  dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-modules-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: yarn-modules-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
      - persist_to_workspace:
          root: /tmp
          paths:
            - workspace

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp
      - run: yarn test:unit

  build:
    <<: *defaults
    environment:
      NODE_ENV: production
    steps:
      - attach_workspace:
          at: /tmp
      - run: yarn build --mode production

  deploy:
    <<: *defaults
    environment:
      NODE_ENV: production
    steps:
      - attach_workspace:
          at: /tmp
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              scp -r -o StrictHostKeyChecking=no -P 2200 ./dist/** deploy@xavierjulien.fr:/volume2/web/mccb_ng/
            fi

workflows:
  version: 2

  mccb_front:
    jobs:
      - dependencies
      - test:
          requires:
            - dependencies
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
