version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10.5.0-stretch-browsers
    environment:
      TZ: "/usr/share/zoneinfo/Europe/Paris"
      NODE_ENV: test
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-modules-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: yarn-modules-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
      - run: yarn test:unit
      - run: yarn build
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              scp -r -o StrictHostKeyChecking=no -P 2200 ./dist/** deploy@xavierjulien.fr:/volume2/web/mccb_ng/
            fi
